Fwmt 452 tm mock
ONSdigital/fwmt-service-mocks pull request #1
Opened 2018-07-30 10:01 UTC by ThomasPootQA

2018-07-30 11:07 UTC, soundargit requested changes

2018-07-30 11:07 UTC, soundargit commented on service_mocks/src/main/resources/application.yml
> +    name: fwmt-service-mock-tm
change it to fwmt-service-mocks since this might have mocks for resource service also.

2018-07-30 11:07 UTC, soundargit commented on service_mocks/src/main/java/uk/gov/ons/fwmt/tm_mock/ws/RawXmlInterceptor.java
> +public class RawXmlInterceptor implements SoapEndpointInterceptor {
This functionality would be needed in JobService client area to log request, response and fault.
Do we need this in Mock service?

2018-07-30 11:07 UTC, soundargit commented on service_mocks/src/main/java/uk/gov/ons/fwmt/tm_mock/ws/RawXmlInterceptor.java
> +    wsLogger.currentMessage.get().requestRawHtml = outputStream.toString();
why can't we print the message directly here?
why do you pass the wslogger around?

same for response and fault?

2018-07-30 11:07 UTC, soundargit commented on service_mocks/src/main/java/uk/gov/ons/fwmt/tm_mock/ws/OutgoingWs.java
> +      @RequestPayload JAXBElement<UpdateVisitStatusRequest> request) {
is the response payload  void?

2018-07-30 11:07 UTC, soundargit commented on service_mocks/src/main/java/uk/gov/ons/fwmt/tm_mock/ws/GenericOutgoingWs.java
> +  // This endpoint doesn't work because of how Spring reacts to the message, instead of the SOAPAction
Does the problem still exist?

2018-07-30 11:07 UTC, soundargit commented on service_mocks/src/main/java/uk/gov/ons/fwmt/tm_mock/logging/WsLogger.java
> +public class WsLogger {
may not be required?

2018-07-30 11:07 UTC, soundargit commented on service_mocks/src/main/java/uk/gov/ons/fwmt/tm_mock/SwaggerConfig.java
> +                .apis( RequestHandlerSelectors.basePackage("uk.gov.ons.fwmt.tm_mock"))
change it to service_mocks.

2018-07-30 11:07 UTC, soundargit commented on service_mocks/settings.gradle
> +rootProject.name = 'tm_mock'
change it to service_mocks

2018-07-31 08:05 UTC, ThomasPootQA commented on service_mocks/src/main/resources/application.yml
> +    name: fwmt-service-mock-tm
This has been done.

2018-07-31 08:07 UTC, ThomasPootQA commented on service_mocks/src/main/java/uk/gov/ons/fwmt/tm_mock/ws/GenericOutgoingWs.java
> +  // This endpoint doesn't work because of how Spring reacts to the message, instead of the SOAPAction
Currently there's a problem with Spring appearing to outright ignore the SOAPAction, instead using the class name and namespace of the first object in the SOAP envelope.

For the time being, I'll leave the 'correct' details in a comment.

2018-07-31 08:07 UTC, ThomasPootQA commented on service_mocks/src/main/java/uk/gov/ons/fwmt/tm_mock/SwaggerConfig.java
> +                .apis( RequestHandlerSelectors.basePackage("uk.gov.ons.fwmt.tm_mock"))
This has been done.

2018-07-31 08:07 UTC, ThomasPootQA commented on service_mocks/settings.gradle
> +rootProject.name = 'tm_mock'
This has been done.

2018-07-31 10:57 UTC, soundargit approved these changes
Needs some cleanup later

2018-07-31 10:58 UTC, merged